services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: final-sw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/final-sw
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345

  flyway_postgres:
    image: postgres:16
    container_name: flyway_postgres
    environment:
      POSTGRES_DB: final-sw_test
      POSTGRES_USER: eternagl
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./db/flyway_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  flyway:
    image: flyway/flyway:10
    container_name: flyway
    command: -url=jdbc:postgresql://flyway_postgres:5432/final-sw_test -user=eternagl -password=12345 -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - flyway_postgres